/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.adyapana.gui;

import com.adyapana.model.Load;
import com.adyapana.model.MySQL;
import com.adyapana.model.SystemConfigData;
import com.adyapana.model.timeDate;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 1zt
 */
public class TeacherEnrollmentForSubject extends javax.swing.JFrame {

    /**
     * Creates new form IPDTreatment
     */
    public TeacherEnrollmentForSubject() {
        initComponents();
        setLocationRelativeTo(null);
        timeDate td = new timeDate();
        td.timeAndDate(jLabel14);
        labal_un.setText(SystemConfigData.getActiveUser());
        labal_ut.setText(SystemConfigData.getUserType());

        Load l = new Load();
        l.loadClasses(jComboBox1);
        l.loadSubject(combo_sub);
        l.loadTeacher(combo_teach);
        loadID();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labal_un = new javax.swing.JLabel();
        labal_ut = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        combo_teach = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();
        combo_sub = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Teacher Enrollment For Subject");

        labal_un.setText("UserName");

        labal_ut.setText("UserType");

        jLabel14.setText("time");

        jButton2.setText("Back To Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel3.setText("Teacher");

        txt_id.setEditable(false);
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Teacher NIC", "Teacher Name", "Subject", "Time From", "Time To", "Class", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Subject");

        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Search Through Date");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Class");

        jLabel6.setText("Time Slote From");

        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", " ", " " }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "00", "05", "10", "15", "20", "25", "30", "35", "45", "50", "55", " " }));

        jLabel7.setText("Date");

        jLabel8.setText("Hour");

        jLabel9.setText("Minites");

        jButton6.setText("Refreash");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel10.setText("Hour");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", " ", " " }));

        jLabel11.setText("Minites");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "00", "05", "10", "15", "20", "25", "30", "35", "45", "50", "55", " " }));

        jLabel12.setText("To");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labal_ut)
                            .addComponent(labal_un))
                        .addGap(283, 283, 283)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(266, 266, 266)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_teach, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_id, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(combo_sub, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labal_un)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labal_ut)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combo_teach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(combo_sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton3)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed

    }//GEN-LAST:event_txt_idActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed

        try {
            String id = txt_id.getText();

            String clas = jComboBox1.getSelectedItem().toString();
            String hour = jComboBox2.getSelectedItem().toString();
            String minites = jComboBox3.getSelectedItem().toString();
            String hourTo = jComboBox4.getSelectedItem().toString();
            String minitesTo = jComboBox5.getSelectedItem().toString();

            SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd");

            String date = null;
            String date_time = null;

            String dateTo = null;
            String date_timeTo = null;

            if (id.equals("")) {
                JOptionPane.showMessageDialog(this, "Please Recheck your id", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (combo_teach.getSelectedItem().toString().equals("Select")) {
                JOptionPane.showMessageDialog(this, "Please Select a Teacher", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (combo_sub.getSelectedItem().toString().equals("Select")) {
                JOptionPane.showMessageDialog(this, "Please Select a Subject", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (clas.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Please Select a Class", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (jDateChooser1.getDate().equals(null)) {
                JOptionPane.showMessageDialog(this, "Please Select a Date From", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (jDateChooser2.getDate().equals(null)) {
                JOptionPane.showMessageDialog(this, "Please Select a Date To", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (hour.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Please Select Hour From!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (minites.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Please Select Minites From!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (minitesTo.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Please Select Minites To!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (hourTo.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Please Select Hour To!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {

                String teacherNIC = combo_teach.getSelectedItem().toString().split("_")[0];
                String teacherName = combo_teach.getSelectedItem().toString().split("_")[1];
                String subject = combo_sub.getSelectedItem().toString();
                String subjectId = combo_sub.getSelectedItem().toString().split("_")[0];

                date = sdf2.format(jDateChooser1.getDate());
                date_time = date + " " + hour;
                date_time += ":" + minites + ":00";

                dateTo = sdf2.format(jDateChooser2.getDate());
                date_timeTo = dateTo + " " + hourTo;
                date_timeTo += ":" + minites + ":00";

                ResultSet Id_rs = MySQL.search("SELECT * FROM teacher_has_subject WHERE id = '" + id + "'");

                if (Id_rs.next()) {
                    JOptionPane.showMessageDialog(this, "Id is Already Define", "Warning", JOptionPane.WARNING_MESSAGE);
                } else {

                    ResultSet classRs = MySQL.search("SELECT * FROM class WHERE class.name = '" + clas + "'");
                    classRs.next();
                    String classId = classRs.getString("id");

                    MySQL.iud("INSERT INTO teacher_has_subject (teacher_nic,subject_id,timeslotefrom,timesloteto,class_id,status_id) VALUES ('" + teacherNIC + "','" + subjectId + "','" + date_time + "','" + date_timeTo + "','" + classId + "','1')");
                    clearField();
                    JOptionPane.showMessageDialog(this, "Success", "success", JOptionPane.INFORMATION_MESSAGE);
                }

            }

        } catch (NullPointerException n) {
            JOptionPane.showMessageDialog(this, "Please Select a Date", "Warning", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String id = txt_id.getText();

            if (id.equals("")) {
                JOptionPane.showMessageDialog(this, "Please Recheck your id", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {

                String toDay = jLabel14.getText();

                ResultSet rs = MySQL.search("SELECT * FROM teacher_has_subject WHERE timeslotefrom >= '" + toDay + "' AND id ='" + id + "';");

                if (!rs.next()) {
                    JOptionPane.showMessageDialog(this, "You can not delete this", "Warning", JOptionPane.WARNING_MESSAGE);
                } else {

//                    MySQL.iud("UPDATE teacher_has_subject SET status_id='2' WHERE id = '" + id + "'");
                    MySQL.iud("DELETE FROM teacher_has_subject WHERE id = '" + id + "'");
                    clearField();
                    JOptionPane.showMessageDialog(this, "Success", "success", JOptionPane.INFORMATION_MESSAGE);
                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            if (jDateChooser1.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Please Select a Date From", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (jDateChooser2.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Please Select a Date To", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf2.format(jDateChooser1.getDate());
                String dateTo = sdf2.format(jDateChooser2.getDate());
                ResultSet rs = MySQL.search("SELECT * FROM teacher_has_subject WHERE timeslotefrom LIKE '" + date + "%' AND timesloteto LIKE '" + dateTo + "%'");
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                dtm.setRowCount(0);

                while (rs.next()) {
                    Vector v = new Vector();
                    v.add(rs.getString("id"));
                    v.add(rs.getString("teacher_nic"));

                    ResultSet teacgRs = MySQL.search("SELECT * FROM teacher WHERE teacher.nic = '" + rs.getString("teacher_nic") + "'");
                    teacgRs.next();
                    String teachName = teacgRs.getString("fname") + " " + teacgRs.getString("lname");

                    v.add(teachName);

                    ResultSet subRs = MySQL.search("SELECT * FROM subject WHERE subject.id = '" + rs.getString("subject_id") + "'");
                    subRs.next();
                    String subName = subRs.getString("id") + "_" + subRs.getString("name");

                    v.add(subName);
                    v.add(rs.getString("timeslotefrom"));
                    v.add(rs.getString("timesloteto"));

                    ResultSet classRs = MySQL.search("SELECT * FROM class WHERE class.id = '" + rs.getString("class_id") + "'");
                    classRs.next();
                    String className = classRs.getString("name");

                    v.add(className);
                    v.add(new Load().status(rs.getString("status_id")));

                     dtm.addRow(v);
                }

               

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            String id = txt_id.getText();

            String clas = jComboBox1.getSelectedItem().toString();
            String hour = jComboBox2.getSelectedItem().toString();
            String minites = jComboBox3.getSelectedItem().toString();
            String hourTo = jComboBox4.getSelectedItem().toString();
            String minitesTo = jComboBox5.getSelectedItem().toString();

            SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd");

            String date = null;
            String date_time = null;

            String dateTo = null;
            String date_timeTo = null;

            if (id.equals("")) {
                JOptionPane.showMessageDialog(this, "Please Recheck your id", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (combo_teach.getSelectedItem().toString().equals("Select")) {
                JOptionPane.showMessageDialog(this, "Please Select a Teacher", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (combo_sub.getSelectedItem().toString().equals("Select")) {
                JOptionPane.showMessageDialog(this, "Please Select a Subject", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (clas.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Please Select a Class", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (jDateChooser1.getDate().equals(null)) {
                JOptionPane.showMessageDialog(this, "Please Select a Date From", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (jDateChooser2.getDate().equals(null)) {
                JOptionPane.showMessageDialog(this, "Please Select a Date To", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (hour.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Please Select Hour From!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (minites.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Please Select Minites From!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (minitesTo.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Please Select Minites To!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (hourTo.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Please Select Hour To!", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {

                String teacherNIC = combo_teach.getSelectedItem().toString().split("_")[0];
                String teacherName = combo_teach.getSelectedItem().toString().split("_")[1];
                String subject = combo_sub.getSelectedItem().toString();
                String subjectId = combo_sub.getSelectedItem().toString().split("_")[0];

                date = sdf2.format(jDateChooser1.getDate());
                date_time = date + " " + hour;
                date_time += ":" + minites + ":00";

                dateTo = sdf2.format(jDateChooser2.getDate());
                date_timeTo = dateTo + " " + hourTo;
                date_timeTo += ":" + minites + ":00";

                String toDay = jLabel14.getText();

                ResultSet rs = MySQL.search("SELECT * FROM teacher_has_subject WHERE timeslotefrom >= '" + toDay + "' AND id ='" + id + "';");

                if (!rs.next()) {
                    JOptionPane.showMessageDialog(this, "You can not update this", "Warning", JOptionPane.WARNING_MESSAGE);
                } else {

                    ResultSet classRs = MySQL.search("SELECT * FROM class WHERE class.name = '" + clas + "'");
                    classRs.next();
                    String classId = classRs.getString("id");

                    MySQL.iud("UPDATE teacher_has_subject SET teacher_nic='" + teacherNIC + "', subject_id ='" + subjectId + "' , timeslotefrom='" + date_time + "' ,timesloteto='" + date_timeTo + "', class_id ='" + classId + "' WHERE id = '" + id + "'");
                    clearField();
                    JOptionPane.showMessageDialog(this, "Success", "success", JOptionPane.INFORMATION_MESSAGE);
                }

            }

        } catch (NullPointerException n) {
            JOptionPane.showMessageDialog(this, "Please Select a Date", "Warning", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1KeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int selectRow = jTable1.getSelectedRow();
        String id = dtm.getValueAt(selectRow, 0).toString();
        String tnic = dtm.getValueAt(selectRow, 1).toString();
        String tname = dtm.getValueAt(selectRow, 2).toString();
        String subject = dtm.getValueAt(selectRow, 3).toString();
        String time = dtm.getValueAt(selectRow, 4).toString();
        String timeTo = dtm.getValueAt(selectRow, 5).toString();
        String clas = dtm.getValueAt(selectRow, 6).toString();

        txt_id.setText(id);
        combo_teach.setSelectedItem(tnic + "_" + tname);
        combo_sub.setSelectedItem(subject);
        jComboBox1.setSelectedItem(clas);
        try {
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse(time);
            jDateChooser1.setDate(date);
            String h1 = time.split(" ")[1];
            String h = h1.split(":")[0];

            jComboBox2.setSelectedItem(h);

            String m = time.split(":")[1];
            jComboBox3.setSelectedItem(m);

            Date dateTo = new SimpleDateFormat("yyyy-MM-dd").parse(timeTo);
            jDateChooser2.setDate(dateTo);
            String h2 = timeTo.split(" ")[1];
            String h3 = h2.split(":")[0];

            jComboBox4.setSelectedItem(h3);

            String m1 = time.split(":")[1];
            jComboBox5.setSelectedItem(m1);

        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        TeacherEnrollmentForSubject pr = new TeacherEnrollmentForSubject();
        pr.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        // TODO add your handling code here:
        jDateChooser2.setDate(jDateChooser1.getDate());
    }//GEN-LAST:event_jDateChooser1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherEnrollmentForSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherEnrollmentForSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherEnrollmentForSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherEnrollmentForSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherEnrollmentForSubject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JComboBox<String> combo_sub;
    private javax.swing.JComboBox<String> combo_teach;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labal_un;
    private javax.swing.JLabel labal_ut;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables

    private void loadID() {
        try {
            ResultSet rs = MySQL.search("SELECT MAX(id) AS maxID FROM adyapana.teacher_has_subject");
            rs.next();
            int v = Integer.parseInt(rs.getString("maxID")) + 1;
            txt_id.setText(v + "");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clearField() {
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(0);
        jComboBox5.setSelectedIndex(0);
        combo_sub.setSelectedIndex(0);
        combo_teach.setSelectedIndex(0);
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);
        loadID();
    }

}
